### ISSUE TITLE
Code is throwing error

### ISSUE THREAD

**Issue by protestToViolence** [MuhammadMoinFaisal/Automatic_Number_Plate_Detection_Recognition_YOLOv8#1]
File "predict.py", line 9, in <module>
    from ultralytics.yolo.utils import DEFAULT_CONFIG, ROOT, ops
ImportError: cannot import name 'DEFAULT_CONFIG' from 'ultralytics.yolo.utils'

I have imported the latest git release but still it is not compiling. I have downloaded your pretrained model and video also. Please can you do see this

**Comment by MuhammadMoinFaisal** [comment]
Hi Please try with ultralytics version 8.0.0,, you will not face this issue
